version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_rastreadb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: rastreio
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
